# export tto
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: '0.0.0.0:4317'
      http:
        endpoint: '0.0.0.0:4318'

processors:
  decouple:
  batch:

exporters:
  debug:
    verbosity: detailed
  otlp/cloudificando:
    endpoint: ${env:OTLP_CLOUDIFICANDO_ENDPOINT}
    headers:
      Authorization: 'Bearer ${env:OTLP_CLOUDIFICANDO_TOKEN}'

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, decouple]
      exporters: [debug,otlp/cloudificando]
    metrics:
      receivers: [otlp]
      processors: [batch, decouple]
      exporters: [debug,otlp/cloudificando]
    logs:
      receivers: [otlp]
      processors: [batch, decouple]
      exporters: [debug ,otlp/cloudificando]
  telemetry:
    metrics:
      address: localhost:8888