# export tto
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: '0.0.0.0:4317'

processors:
  decouple:
exporters:
  otlp/cloudificando:
    endpoint: ${env:OTLP_CLOUDIFICANDO_ENDPOINT}
    headers:
      Authorization: 'Bearer ${env:OTLP_CLOUDIFICANDO_TOKEN}'

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [decouple]
      exporters: [otlp/cloudificando]
    metrics:
      receivers: [otlp]
      processors: [decouple]
      exporters: [otlp/cloudificando]
    logs:
      receivers: [otlp]
      processors: [decouple]
      exporters: [otlp/cloudificando]
